apiVersion: v1
kind: Service
metadata:
  name: favorites-service
spec:
  type: NodePort
  selector:
    app: favorites-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30080
