apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-router
  template:
    metadata:
      labels:
        app: gateway-router
    spec:
      containers:
        - name: gateway-router
          image: sagariprashanth/gateway-router:2.0
          imagePullPolicy: IfNotPresent
          # image: sagariprashanth/gateway-router:1.0
          # imagePullPolicy: Always
          ports:
            - containerPort: 8889
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-router
spec:
  type: NodePort
  selector:
    app: gateway-router
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 8889
      nodePort: 32009         