apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-service
  template:
    metadata:
      labels:
        app: reviews-service
    spec:
      containers:
        - name: reviews-service
          image: sagariprashanth/reviews-service:2.0
          imagePullPolicy: IfNotPresent
          #image: sagariprashanth/favorites-service:1.0
          #imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/reviews_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service
spec:
  type: NodePort
  selector:
    app: reviews-service
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30081
